In [ ]:
import wave
import struct
import librosa
import numpy as np

path = 'E:/datasets/data_thchs30/data/A2_0.wav'

In [ ]:
wave_file = wave.open(path, 'r')
channels = wave_file.getnchannels()  #声道数
samp_width = wave_file.getsampwidth()  #采样大小
frame_rate = wave_file.getframerate()  #帧率
numframes = wave_file.getnframes()  #总帧数

print("channel", channels)  #声道数
print('samp_width', samp_width)  #采样大小2B 16bit
print('frame_rate', frame_rate)  #8000 帧率8000fps
print('numframes', numframes)  #总帧数=帧率*时间=8000fps*10s=80000f

for i in range(500):
    frame = wave_file.readframes(1)  #读取1帧音频数据，可能包含多个声道信息
    print(frame,struct.unpack("h", frame[0:2])[0])
    #struct.unpack("h",frame[0:2])将二进制数据转化成10进制（16bit有符号整数）因为这里采样大小是16bit
wave_file.close()

In [ ]:
with open(path, 'rb') as f:
    frames = f.read()
    print(frames[44:])

In [10]:
import array


def read_pcm16(data: bytes):
    """
    convert bytes into array of pcm_s16le data
    :param data: PCM format bytes
    :return:
    """
    shortArray = array.array('h')  # int16
    # header of wav file
    info = data[:44]
    frames = data[44:]
    name, data_lengths, _, _, _, _, channels, sample_rate, bit_rate, block_length, sample_bit, _, pcm_length = struct.unpack_from(
        '<4sL4s4sLHHLLHH4sL', info)
    # shortArray each element is 16bit
    shortArray.frombytes(frames)  # struct.unpack
    data = np.array(shortArray)
    # 缩放
    data = data / 2 ** 15
    return data, sample_rate

In [11]:
data, sample_rate = read_pcm16(frames)

In [16]:
len(data), data, data * (2 ** 15)

(157000,
 array([-0.0090332 , -0.01293945, -0.01196289, ..., -0.01202393,
        -0.01156616, -0.01190186]),
 array([-296., -424., -392., ..., -394., -379., -390.]))

In [ ]:
data * (1 << 15), max(data * (1 << 15))

In [15]:
librosa.load(path, sr=16000)

(array([-0.0090332 , -0.01293945, -0.01196289, ..., -0.01202393,
        -0.01156616, -0.01190186], dtype=float32),
 16000)

In [29]:
s = "我 是 中 国 人"
b = s.encode('utf-8')

In [22]:
struct.unpack("h", s.encode('utf-8')[:3])

error: unpack requires a buffer of 2 bytes

In [25]:
shortArray = array.array('h')
shortArray.frombytes(b)

ValueError: bytes length not a multiple of item size

In [30]:
b

b'\xe6\x88\x91 \xe6\x98\xaf \xe4\xb8\xad \xe5\x9b\xbd \xe4\xba\xba'

In [31]:
int.from_bytes(b, byteorder='big')

5141068051224587196122899090252126564875811514

In [33]:
int.from_bytes(b[0:3], byteorder='little')

9537766

In [34]:
len(frames)

314044